### PR TITLE
[Reviewer: AJL] Changing shared_config modification in HEAT templates

### PR DESCRIPTION
**Pull request by RobDover**
To be clear, I have not live tested this yet. I figure that should wait until you're done with the Openstack rig.

Having said that, I think the changes here are pretty low-risk in that this is the new canonical way to do this, so if this code has bugs they'd have shown up somewhere else already at this point.

### CODE REVIEW

**Comment by RobDover** [comment]
Fixes Metaswitch/clearwater-issues#2653

**Comment by johadalin** [comment]
Given https://github.com/Metaswitch/clearwater-issues/issues/2659 i don't think this is good to go. Presumably whatever issue is plaguing chef will likely also hit us here, so we'll want the fix, and we'll want to do some testing. Once this is ready for test, we can work out a brief gap in the load testing to spin up a set of nodes on the rig.
Also, just to check, you're presumably looking into the other half of the issue separately.

**Comment by johadalin** [comment]
@kenferguson has this now been properly live tested? If so,  all good, and we can delete the branch as well :smiley:

**Comment by kenferguson** [comment]
Yep - all good.

**Pull request merged**
